//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gallery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///
        ///    &lt;!--Style for Gallery--&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            line-height: 1.4;
        ///            font-size: 18px;
        ///            padding: 20px;
        ///            margin: 0 auto;
        ///            background: black;
        ///        }
        ///
        ///        .floatImage {
        ///            display: inline-block;
        ///            width:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Infinite Scroll PACKAGED v3.0.6
        /// * Automatically add next page
        /// *
        /// * Licensed GPLv3 for open source use
        /// * or Infinite Scroll Commercial License for commercial use
        /// *
        /// * https://infinite-scroll.com
        /// * Copyright 2018 Metafizzy
        /// */
        ///
        ///!function(t,e){&quot;function&quot;==typeof define&amp;&amp;define.amd?define(&quot;jquery-bridget/jquery-bridget&quot;,[&quot;jquery&quot;],function(i){return e(t,i)}):&quot;object&quot;==typeof module&amp;&amp;module.exports?module.exports=e(t,require(&quot;jquery&quot;)):t.jQueryBridget=e(t,t.jQuery)}(window,function(t,e){&quot;u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string infinite_scroll_pkgd_min {
            get {
                return ResourceManager.GetString("infinite_scroll_pkgd_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e)}:t(e)}(&quot;undefined&quot;!=typeof window?window:this,function(C,e){&quot;use strict&quot;;var t=[],E=C.document,r=Object.getPrototypeOf,s=t.slice,g=t.concat,u=t.push,i=t.indexOf,n={},o=n.toString,v=n.hasOwnProperty,a=v.toStri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_3_4_1_min {
            get {
                return ResourceManager.GetString("jquery_3_4_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;topbar&quot;&gt;
        ///    &lt;table&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;img class=&quot;avatar-image&quot; src=&quot;{AVATARURL}&quot;&gt;
        ///            &lt;/td&gt;
        ///
        ///            &lt;td style=&quot;color: white;&quot;&gt;{SENDER}&lt;br&gt;{DATE}&lt;/td&gt;
        ///
        ///            &lt;td&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///            &lt;td style=&quot;color: white;&quot;&gt;{MESSAGE}&lt;/td&gt;
        ///
        ///            &lt;td&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/td&gt;
        ///            &lt;td&gt;{LIKERS}&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/table&gt;
        ///
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;mainblock&quot;&gt;
        ///    &lt;img class=&quot;gm-image&quot; src=&quot;{IMAGE}&quot;&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string popup {
            get {
                return ResourceManager.GetString("popup", resourceCulture);
            }
        }
    }
}
